name: Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install Mise
      run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

    - name: Install Dependencies
      run: |
        mise install

    - name: Run Build
      run: |
        pnpm install
        pnpm build

    - name: Upload build artifacts (main only)
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: actions/upload-artifact@v3
      with:
        name: build-assets
        path: dist/
